server:
  port: 8077
spring:
  datasource:
    username: java38
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/carbike?serverTimezone=UTC
    #关于freemarker配置
  freemarker:
    #关闭缓存
    cache: false
    suffix: .html
  redis:
    host: 192.168.43.251
    port: 6381
    database: 0
mybatis:
  type-aliases-package: com.liu.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
